import Head from "next/head"
import Link from "next/link"
import style from "../styles/404.module.css"

export default function NotFound() {
    return (<>
        <Head>
            <title>Next Cats - Not Found</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/cat.ico" />
        </Head>

    

        <div className={style.notFound}>
        <h1>404 - Not Found</h1>
        <Link href="/">
        <a>
        <ion-icon name="arrow-forward-outline"></ion-icon>  Voltar ao inicio
        </a>
        </Link>
        </div>

       
    </>)
}