import Image from "next/image"
import Head from "next/head"
import styles from "../../styles/Breeds.module.css"
import Link from "next/link"
import CatBreedPicture from "../../components/CatBreedPicture"

export async function getStaticProps() {
  const data = await fetch('https://api.thecatapi.com/v1/breeds')

  const breeds = await data.json()



  return {
    props: { breeds },
  }
}




export default function Breeds({ breeds }) {

  return (
    <>
      <Head>
        <title>Next Cats - Raças</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Raças de gato:</h1>
      <div className={styles.catsContainer}>
        {breeds.map((breed) => (<>

              <CatBreedPicture link={{pathname: '/breeds/[breedid]',query: { breedid: breed.id},}} id={breed.id} name={breed.name}  image= {breed.image && breed.image.url ? breed.image.url : "/images/404cat.jpg" } />
    
        </>))}
      </div>
    </>
  )
}